function [simimage] = getSimilarPair(img)



imageAugmenter = imageDataAugmenter( ...
    'RandRotation',[-15,15], ...
    'RandXTranslation',[-20 20], ...
    'RandYTranslation',[-20 20], ...
    'RandXReflection',1,...
    'RandYReflection',0,...
    'RandXShear',[-5,5],...
    'RandYShear',[-5,5],...
    'RandScale',[0.8 1]);
imgSize = [600,600,3];
augimds = augmentedImageDatastore(imgSize,img,'DataAugmentation',imageAugmenter);


img = read(augimds);

simimage=img{1,1};
simimage=simimage{1};

end

